# Generated by Django 5.0.7 on 2024-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='augmented_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
